import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/navbar/Navbar";
import { AppWrapper } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          <Toaster />
          <div className="sticky top-0 sm:hidden block">
            <Navbar />
          </div>
          <div className="flex h-screen gap-[1.5vw] overflow-y-hidden">
            <div className="min-w-[200px] sm:block hidden">
              <Sidebar />
            </div>
            <div className=" flex-grow ">{children}</div>
          </div>
        </AppWrapper>
      </body>
    </html>
  );
}
