import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Navbar from "@/components/navbar/Navbar";
import AuthProvider from "@/context/AuthProvider";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Management App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} md:bg-gray-100`}>
        <AuthProvider>
          <div className="flex h-screen gap-5  overflow-y-hidden md:mr-6 ">
            <div className=" md:block hidden min-w-[15vw]">
              <Sidebar />
            </div>

            <div className=" flex flex-col md:gap-4 md:w-[85vw] w-full   ">
              <Navbar />
              <div className="bg-white p-2 rounded-lg ">{children}</div>
            </div>
          </div>

          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
